import { z } from 'zod';

export const PLATFORM_IDS = [
  'instagram',
  'twitter',
  'linkedin',
  'facebook',
  'gmail',
  'whatsapp',
  'youtube',
  'research',
  'chatgpt',
  'gemini',
];

export const PlatformIdSchema = z.enum(PLATFORM_IDS);
export const BrowserModeSchema = z.enum(['attached', 'managed']);

export const QuietHoursSchema = z.object({
  timezone: z.string(),
  windows: z.array(
    z.object({
      start: z.string(),
      end: z.string(),
    }),
  ),
});

export const LeadSourceConfigSchema = z.object({
  sourceType: z.enum(['search_engine', 'target_site']),
  engine: z.enum(['duckduckgo', 'google']).optional(),
  query: z.string().optional(),
  domains: z.array(z.string()).optional(),
  browserMode: z.literal('managed'),
});

export const StopRuleSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('daily_cap_reached') }),
  z.object({ type: z.literal('positive_reply_target'), count: z.number().int().positive() }),
  z.object({ type: z.literal('consecutive_failures'), count: z.number().int().positive() }),
  z.object({ type: z.literal('manual_stop') }),
  z.object({ type: z.literal('auth_invalid') }),
]);

export const CampaignCapsSchema = z.object({
  perPlatformDailyActions: z.record(z.string(), z.number().int().nonnegative()).default({}),
  perPlatformDailyMessages: z.record(z.string(), z.number().int().nonnegative()).default({}),
  maxConcurrentTabs: z.number().int().positive().default(4),
  maxConcurrentConversations: z.number().int().positive().default(2),
});

export const PlanStepSchema = z.object({
  id: z.string(),
  platform: PlatformIdSchema,
  browserMode: BrowserModeSchema,
  action: z.string(),
  args: z.record(z.string(), z.unknown()).default({}),
  successCriteria: z.string(),
  retryPolicy: z.object({
    maxAttempts: z.number().int().positive().default(2),
    replanOnFailure: z.boolean().default(true),
  }),
});

export const ExecutionPlanSchema = z.object({
  taskId: z.string(),
  objective: z.string(),
  targetPlatforms: z.array(PlatformIdSchema),
  steps: z.array(PlanStepSchema),
});

export const CampaignSchema = z.object({
  id: z.string(),
  name: z.string(),
  objective: z.string(),
  platforms: z.array(PlatformIdSchema),
  browserStrategy: z.object({
    defaultMode: z.enum(['attached', 'managed', 'auto']).default('auto'),
    perPlatform: z.record(z.string(), BrowserModeSchema).default({}),
  }),
  schedules: z.array(
    z.object({
      id: z.string(),
      label: z.string(),
      cadenceMinutes: z.number().int().positive(),
    }),
  ),
  caps: CampaignCapsSchema,
  quietHours: QuietHoursSchema,
  targets: z.object({
    usernames: z.array(z.string()).default([]),
    emails: z.array(z.string()).default([]),
    keywords: z.array(z.string()).default([]),
    notes: z.string().default(''),
  }),
  leadSources: z.array(LeadSourceConfigSchema).default([]),
  stopRules: z.array(StopRuleSchema).default([]),
  contentPolicy: z.object({
    tone: z.string().default('Casual and brief'),
    outreachGoal: z.string().default('Get a meeting'),
    allowAutonomousReplies: z.boolean().default(true),
  }),
  status: z.enum(['draft', 'active', 'paused', 'stopped']).default('draft'),
});

export const INSTAGRAM_ACTION_SECTIONS = [
  {
    id: 'account_analysis',
    flow: 'shared',
    label: 'Account Analysis',
    actions: [
      { label: 'Analyze Account Type', operation: 'analyze_instagram_account_type' },
      { label: 'Analyze My Profile', operation: 'analyze_instagram_profile' },
      { label: 'Analyze User Profile', operation: 'analyze_user_profile' },
      { label: 'Connect Instagram', operation: 'connect_instagram_account' },
      { label: 'Refresh Permissions', operation: 'refresh_permissions' },
      { label: 'Sync Profile', operation: 'sync_profile' },
      { label: 'View Account Status', operation: 'view_account_status' },
      { label: 'Open Profile', operation: 'open_profile' },
      { label: 'Edit Profile', operation: 'edit_profile' },
      { label: 'Change Bio', operation: 'change_bio' },
      { label: 'Change Profile Photo', operation: 'change_profile_photo' },
    ],
  },
  {
    id: 'normal_navigation',
    flow: 'normal',
    label: 'Navigation',
    actions: [
      { label: 'Open Settings', operation: 'open_settings' },
      { label: 'Open More Menu', operation: 'open_more_menu' },
      { label: 'Open Activity', operation: 'open_activity' },
      { label: 'Open Saved', operation: 'open_saved' },
      { label: 'Switch Appearance', operation: 'switch_appearance' },
      { label: 'Report a Problem', operation: 'report_problem' },
      { label: 'Switch Accounts', operation: 'switch_accounts' },
      { label: 'Logout', operation: 'logout', sensitive: true },
      { label: 'Open Search Results', operation: 'open_search_results' },
      { label: 'Open Notifications', operation: 'open_notifications' },
      { label: 'Open Explore', operation: 'open_explore' },
      { label: 'Open Reels', operation: 'open_reels' },
      { label: 'View Suggestions', operation: 'view_suggestions' },
      { label: 'View Feed Posts', operation: 'view_feed_posts' },
      { label: 'Switch to Professional', operation: 'switch_professional_account', sensitive: true },
    ],
  },
  {
    id: 'normal_content',
    flow: 'normal',
    label: 'Create',
    actions: [
      { label: 'Create Post', operation: 'create_post_draft' },
      { label: 'Upload Media', operation: 'upload_media' },
      { label: 'Create Media Flow', operation: 'create_media_publish_flow' },
      { label: 'Write Caption', operation: 'write_caption' },
      { label: 'Add Hashtags', operation: 'add_hashtags' },
      { label: 'Add Location', operation: 'add_location' },
      { label: 'Tag Users', operation: 'tag_users' },
      { label: 'Save Draft', operation: 'save_draft' },
      { label: 'Schedule Post', operation: 'schedule_post' },
      { label: 'Publish Now', operation: 'publish_now', sensitive: true },
      { label: 'Create Reel', operation: 'create_reel' },
      { label: 'Publish Reel', operation: 'publish_reel', sensitive: true },
      { label: 'Create Story', operation: 'create_story' },
      { label: 'Publish Story', operation: 'publish_story', sensitive: true },
      { label: 'Start Live', operation: 'start_live', sensitive: true },
      { label: 'Delete Post', operation: 'delete_post', sensitive: true },
      { label: 'Archive Post', operation: 'archive_post', sensitive: true },
      { label: 'Pin Post', operation: 'pin_post' },
    ],
  },
  {
    id: 'normal_engagement',
    flow: 'normal',
    label: 'Stories, Feed, Profiles',
    actions: [
      { label: 'View Stories', operation: 'view_stories' },
      { label: 'Reply to Story', operation: 'reply_to_story' },
      { label: 'Comment on Story', operation: 'comment_on_story' },
      { label: 'Like Post', operation: 'like_post' },
      { label: 'Comment Post', operation: 'comment_post' },
      { label: 'Reply to Comment', operation: 'reply_to_post_comment' },
      { label: 'Open Other Profile Posts', operation: 'open_user_posts' },
      { label: 'Open Videos/Reels', operation: 'open_user_videos' },
      { label: 'Repost', operation: 'repost_post' },
      { label: 'Delete Reel', operation: 'delete_reel', sensitive: true },
      { label: 'Delete Story', operation: 'delete_story', sensitive: true },
      { label: 'Add Story Highlight', operation: 'add_story_highlight' },
    ],
  },
  {
    id: 'normal_messages',
    flow: 'normal',
    label: 'Messages',
    actions: [
      { label: 'Open Inbox', operation: 'open_inbox' },
      { label: 'Open Messages List', operation: 'open_messages_list' },
      { label: 'Open Requests', operation: 'open_requested_messages' },
      { label: 'Reply to DM', operation: 'reply_to_dm' },
      { label: 'Send Media', operation: 'send_dm_media' },
      { label: 'Use Saved Reply', operation: 'use_saved_reply' },
      { label: 'Accept Request', operation: 'accept_message_request' },
      { label: 'Delete Request', operation: 'delete_message_request', sensitive: true },
      { label: 'Blur Request', operation: 'blur_message_request' },
      { label: 'Assign to Human', operation: 'assign_conversation_to_human' },
      { label: 'Mark Resolved', operation: 'mark_conversation_resolved' },
    ],
  },
  {
    id: 'comments',
    flow: 'normal',
    label: 'Comments',
    actions: [
      { label: 'Load Comments', operation: 'load_comments' },
      { label: 'Reply', operation: 'reply_to_comment' },
      { label: 'Hide', operation: 'hide_comment', sensitive: true },
      { label: 'Unhide', operation: 'unhide_comment' },
      { label: 'Delete', operation: 'delete_comment', sensitive: true },
      { label: 'Disable Comments', operation: 'disable_comments', sensitive: true },
      { label: 'Enable Comments', operation: 'enable_comments' },
      { label: 'Private Reply', operation: 'send_private_reply' },
    ],
  },
  {
    id: 'moderation',
    flow: 'normal',
    label: 'Moderation',
    actions: [
      { label: 'Detect Spam', operation: 'detect_spam' },
      { label: 'Hide Spam', operation: 'hide_spam_comment', sensitive: true },
      { label: 'Flag Negative', operation: 'flag_negative_comment' },
      { label: 'Escalate Issue', operation: 'escalate_issue' },
      { label: 'Block User', operation: 'block_user', sensitive: true },
      { label: 'Restrict User', operation: 'restrict_user', sensitive: true },
      { label: 'Report User', operation: 'report_user', sensitive: true },
      { label: 'Remove Follower', operation: 'remove_follower', sensitive: true },
    ],
  },
  {
    id: 'professional_messages',
    flow: 'professional',
    label: 'Professional Messages',
    actions: [
      { label: 'Open Primary', operation: 'open_primary_messages' },
      { label: 'Open General', operation: 'open_general_messages' },
      { label: 'Open Requests', operation: 'open_requested_messages' },
      { label: 'Move to Primary', operation: 'move_request_primary' },
      { label: 'Move to General', operation: 'move_request_general' },
      { label: 'Move to Channel', operation: 'move_request_channel' },
      { label: 'Accept Request', operation: 'accept_message_request' },
      { label: 'Delete Request', operation: 'delete_message_request', sensitive: true },
    ],
  },
  {
    id: 'professional_create',
    flow: 'professional',
    label: 'Professional Create',
    actions: [
      { label: 'Create Post', operation: 'create_post_draft' },
      { label: 'Create Live Video', operation: 'create_live_video', sensitive: true },
      { label: 'Create Ad', operation: 'create_ad', sensitive: true },
      { label: 'Open AI Create', operation: 'open_ai_create' },
    ],
  },
  {
    id: 'professional_dashboard',
    flow: 'professional',
    label: 'Dashboard',
    actions: [
      { label: 'Open Dashboard', operation: 'open_professional_dashboard' },
      { label: 'Open Insights', operation: 'sync_insights' },
      { label: 'Open Ad Account', operation: 'open_ad_account' },
      { label: 'Open Content', operation: 'open_content_tools' },
      { label: 'Open Ad Tools', operation: 'open_ad_tools' },
      { label: 'Professional Settings', operation: 'open_professional_settings' },
      { label: 'Create Ad', operation: 'create_ad', sensitive: true },
      { label: 'Switch to Normal', operation: 'switch_normal_account', sensitive: true },
    ],
  },
  {
    id: 'professional_leads',
    flow: 'professional',
    label: 'Leads/CRM',
    actions: [
      { label: 'Qualify Lead', operation: 'qualify_lead' },
      { label: 'Score Lead', operation: 'score_lead' },
      { label: 'Save Lead', operation: 'save_lead' },
      { label: 'Push to CRM', operation: 'push_lead_to_crm' },
      { label: 'Add to Sheet', operation: 'add_lead_to_spreadsheet' },
      { label: 'Create Follow-up', operation: 'create_follow_up' },
    ],
  },
  {
    id: 'analytics',
    flow: 'professional',
    label: 'Analytics',
    actions: [
      { label: 'View Report', operation: 'view_report' },
      { label: 'Export Report', operation: 'export_report' },
      { label: 'Track Post Performance', operation: 'track_post_performance' },
      { label: 'Track Reel Performance', operation: 'track_reel_performance' },
      { label: 'Track Story Performance', operation: 'track_story_performance' },
    ],
  },
  {
    id: 'automation',
    flow: 'professional',
    label: 'Automation',
    actions: [
      { label: 'Create Rule', operation: 'create_automation_rule' },
      { label: 'Enable Rule', operation: 'enable_rule' },
      { label: 'Pause Rule', operation: 'pause_rule' },
      { label: 'Run Workflow', operation: 'run_workflow' },
      { label: 'Approve Action', operation: 'approve_action' },
      { label: 'Reject Action', operation: 'reject_action' },
      { label: 'View Action Log', operation: 'view_action_log' },
    ],
  },
];

export const INSTAGRAM_ACTION_OPERATIONS = [
  ...new Set(INSTAGRAM_ACTION_SECTIONS.flatMap((section) => section.actions.map((action) => action.operation))),
];

export const INSTAGRAM_SENSITIVE_OPERATIONS = [
  ...new Set(INSTAGRAM_ACTION_SECTIONS.flatMap((section) => section.actions.filter((action) => action.sensitive).map((action) => action.operation))),
];

const instagramSingleStepWorkflows = Object.fromEntries(INSTAGRAM_ACTION_OPERATIONS.map((operation) => [operation, [operation]]));

export const TASK_OPERATIONS = [
  'open_workspace',
  'find_leads',
  'send_message',
  'message_batch',
  'lead_and_message',
  'follow_and_message',
  'scrape_and_message',
  'run_campaign',
  'research',
  'scrape_profiles',
  'execute_deep_scrape',
  'scrape_followers',
  'auto_dm',
  'auto_dm_contact',
  'auto_dm_new',
  'like_ai_comment',
  'auto_comment',
  'follow_user',
  'follow_search',
  'join_groups_search',
  'connect',
  'connect_swn',
  'connect_sn',
  'auto_post',
  'bulk_dm_csv',
  'bulk_engage_csv',
  'bulk_follow_csv',
  'open_status',
  'post_status',
  'change_profile_photo',
  'delete_chat',
  'block_user',
  'report_user',
  'map_contacts',
  'gmail_search',
  'gmail_get_context',
  'gmail_get_profile',
  'gmail_reply',
  'open_youtube_studio',
  'open_youtube_content',
  'open_youtube_analytics',
  'open_youtube_community',
  'open_youtube_customization',
  'open_youtube_settings',
  'upload_youtube_video',
  'upload_youtube_short',
  'create_youtube_post',
  'write_youtube_description',
  'ask',
  'chat',
  'generate_image',
  'upload_file',
  'like_post',
  'comment_post',
  'engage_post',
  ...INSTAGRAM_ACTION_OPERATIONS.filter((operation) => ![
    'change_profile_photo',
    'block_user',
    'report_user',
  ].includes(operation)),
];

export const CANONICAL_SKILL_ACTIONS = [
  'open_workspace',
  'open_home',
  'search',
  'apply_filters',
  'scroll_collect',
  'scrape_results',
  'open_result',
  'open_target',
  'scrape_profile',
  'follow',
  'connect',
  'connect_swn',
  'connect_sn',
  'open_message',
  'draft_message',
  'send_message',
  'message_batch',
  'follow_user',
  'follow_search',
  'join_groups_search',
  'engage_post',
  'engage_batch',
  'follow_batch',
  'compose_post',
  'publish_post',
  'review_queue',
  'continue_outreach',
  'extract_context',
  'export_artifact',
  'open_status',
  'post_status',
  'change_profile_photo',
  'delete_chat',
  'block_user',
  'report_user',
  'map_contacts',
  'generate_image',
  // Engagement actions
  'like_post',
  'comment_post',
  // Gmail actions
  'get_context',
  'get_profile_context',
  'reply_to_email',
  // YouTube Studio actions
  'open_youtube_studio',
  'open_youtube_content',
  'open_youtube_analytics',
  'open_youtube_community',
  'open_youtube_customization',
  'open_youtube_settings',
  'upload_youtube_video',
  'upload_youtube_short',
  'create_youtube_post',
  'write_youtube_description',
  ...INSTAGRAM_ACTION_OPERATIONS,
];

const socialCoreActions = [
  'open_workspace',
  'open_home',
  'search',
  'apply_filters',
  'scroll_collect',
  'scrape_results',
  'open_result',
  'open_target',
  'scrape_profile',
  'draft_message',
  'send_message',
  'message_batch',
  'follow_user',
  'engage_post',
  'engage_batch',
  'follow_batch',
  'compose_post',
  'publish_post',
  'review_queue',
  'continue_outreach',
  'extract_context',
  'export_artifact',
  'like_post',
  'comment_post',
];

export const PLATFORM_SKILL_CAPABILITIES = {
  instagram: [
    ...new Set([
      ...socialCoreActions,
      'scrape_followers',
      'map_contacts',
      'change_profile_photo',
      'block_user',
      'report_user',
      ...INSTAGRAM_ACTION_OPERATIONS,
    ]),
  ],
  twitter: [...socialCoreActions, 'map_contacts'],
  linkedin: [...socialCoreActions, 'connect', 'connect_swn', 'connect_sn', 'connect_user', 'connect_with_note', 'map_contacts'],
  facebook: [...socialCoreActions, 'follow_search', 'join_groups_search', 'map_contacts'],
  youtube: [
    'open_workspace',
    'open_home',
    'search',
    'apply_filters',
    'scroll_collect',
    'scrape_results',
    'extract_context',
    'export_artifact',
    'open_youtube_studio',
    'open_youtube_content',
    'open_youtube_analytics',
    'open_youtube_community',
    'open_youtube_customization',
    'open_youtube_settings',
    'upload_youtube_video',
    'upload_youtube_short',
    'create_youtube_post',
    'write_youtube_description',
    'map_contacts',
  ],
  gmail: [
    'open_workspace',
    'search',
    'scroll_collect',
    'scrape_results',
    'open_target',
    'draft_message',
    'send_message',
    'message_batch',
    'review_queue',
    'continue_outreach',
    'extract_context',
    'export_artifact',
    'get_context',
    'get_profile_context',
    'reply_to_email',
    'map_contacts',
  ],
  whatsapp: [
    'open_workspace',
    'search',
    'open_target',
    'draft_message',
    'send_message',
    'message_batch',
    'review_queue',
    'continue_outreach',
    'open_status',
    'post_status',
    'change_profile_photo',
    'delete_chat',
    'block_user',
    'report_user',
    'map_contacts',
  ],
  research: ['search', 'open_result', 'scroll_collect', 'scrape_results', 'extract_context', 'export_artifact'],
  chatgpt: ['open_workspace', 'chat', 'ask', 'generate_image', 'upload_file'],
  gemini:  ['open_workspace', 'chat', 'ask', 'generate_image', 'upload_file'],
  sheets:  ['open_workspace', 'create_sheet', 'write_data', 'export_to_sheet', 'read_sheet'],
};

export const WORKFLOW_TEMPLATES = {
  ...instagramSingleStepWorkflows,
  open_workspace: ['open_workspace'],
  generate_image: ['open_workspace', 'generate_image'],
  chat:           ['open_workspace', 'chat'],
  ask:            ['open_workspace', 'ask'],
  upload_file:    ['open_workspace', 'upload_file'],
  create_sheet:   ['open_workspace', 'create_sheet'],
  write_data:     ['open_workspace', 'write_data'],
  export_to_sheet:['open_workspace', 'export_to_sheet'],
  read_sheet:     ['open_workspace', 'read_sheet'],
  find_leads: ['open_workspace', 'open_home', 'search', 'apply_filters', 'scroll_collect', 'scrape_results', 'export_artifact'],
  scrape_profiles: ['open_workspace', 'open_home', 'search', 'apply_filters', 'scroll_collect', 'scrape_results', 'export_artifact'],
  execute_deep_scrape: ['open_workspace', 'open_home', 'search', 'apply_filters', 'scroll_collect', 'scrape_results', 'open_result', 'scrape_profile', 'extract_context', 'export_artifact'],
  scrape_followers: ['open_workspace', 'open_target', 'scroll_collect', 'scrape_results', 'export_artifact'],
  send_message: ['open_workspace', 'open_target', 'send_message'],
  auto_dm: ['open_workspace', 'open_target', 'send_message'],
  message_batch: ['open_workspace', 'message_batch'],
  bulk_dm_csv: ['open_workspace', 'message_batch'],
  follow_user: ['open_workspace', 'open_target', 'follow_user'],
  follow_search: ['open_workspace', 'follow_search'],
  join_groups_search: ['open_workspace', 'join_groups_search'],
  connect: ['open_workspace', 'open_target', 'connect'],
  connect_swn: ['open_workspace', 'open_target', 'connect_swn'],
  connect_sn: ['open_workspace', 'open_target', 'connect_sn'],
  follow_and_message: ['open_workspace', 'open_target', 'follow_user', 'send_message'],
  lead_and_message: ['open_workspace', 'open_home', 'search', 'apply_filters', 'scroll_collect', 'scrape_results', 'export_artifact', 'message_batch'],
  scrape_and_message: ['open_workspace', 'open_home', 'search', 'apply_filters', 'scroll_collect', 'scrape_results', 'export_artifact', 'message_batch'],
  like_ai_comment: ['open_workspace', 'open_target', 'engage_post'],
  like_post:        ['open_workspace', 'open_target', 'like_post'],
  auto_comment:     ['open_workspace', 'open_target', 'comment_post'],
  bulk_engage_csv: ['open_workspace', 'engage_batch'],
  bulk_follow_csv: ['open_workspace', 'follow_batch'],
  auto_post: ['open_workspace', 'compose_post', 'publish_post'],
  run_campaign: ['open_workspace', 'review_queue', 'continue_outreach'],
  map_contacts: ['open_workspace', 'map_contacts'],
  research: ['search', 'open_result', 'scroll_collect', 'scrape_results', 'extract_context', 'export_artifact'],
  open_status: ['open_workspace', 'open_status'],
  post_status: ['open_workspace', 'post_status'],
  change_profile_photo: ['open_workspace', 'change_profile_photo'],
  delete_chat: ['open_workspace', 'open_target', 'delete_chat'],
  block_user: ['open_workspace', 'open_target', 'block_user'],
  report_user: ['open_workspace', 'open_target', 'report_user'],
  open_youtube_studio: ['open_workspace', 'open_youtube_studio'],
  open_youtube_content: ['open_workspace', 'open_youtube_content'],
  open_youtube_analytics: ['open_workspace', 'open_youtube_analytics'],
  open_youtube_community: ['open_workspace', 'open_youtube_community'],
  open_youtube_customization: ['open_workspace', 'open_youtube_customization'],
  open_youtube_settings: ['open_workspace', 'open_youtube_settings'],
  upload_youtube_video: ['open_workspace', 'upload_youtube_video'],
  upload_youtube_short: ['open_workspace', 'upload_youtube_short'],
  create_youtube_post: ['open_workspace', 'create_youtube_post'],
  write_youtube_description: ['open_workspace', 'write_youtube_description'],
};

export const WORKFLOW_PRESETS = [
  {
    id: 'find_leads',
    label: 'Find leads',
    description: 'Search like a user, scroll results, collect visible profiles, and export an artifact.',
  },
  {
    id: 'scrape_profiles',
    label: 'Scrape profiles',
    description: 'Open search, collect visible people or profile cards, and save context.',
  },
  {
    id: 'follow_user',
    label: 'Follow target',
    description: 'Open a profile and trigger the platform follow/connect action.',
  },
  {
    id: 'follow_search',
    label: 'Follow search results',
    description: 'Search visible people results and follow or add them one by one.',
  },
  {
    id: 'join_groups_search',
    label: 'Join groups',
    description: 'Search visible Facebook groups and click Join one by one.',
  },
  {
    id: 'send_message',
    label: 'DM target',
    description: 'Open a target, draft a contextual message, and send or leave it for review.',
  },
  {
    id: 'follow_and_message',
    label: 'Follow + DM',
    description: 'Open a target, follow/connect, draft a message, then send or leave for review.',
  },
  {
    id: 'lead_and_message',
    label: 'Leads + DMs',
    description: 'Find leads, export the scrape, then process provided usernames one by one.',
  },
  {
    id: 'map_contacts',
    label: 'Profile + Chat Sync',
    description: 'Analyze visible contacts, conversations, sentiment, and profile signals for the dashboard.',
  },
];

export const TaskContextSchema = z.object({
  platform: PlatformIdSchema.optional(),
  operation: z.enum(TASK_OPERATIONS).optional(),
  query: z.string().optional(),
  username: z.string().optional(),
  usernames: z.array(z.string()).default([]),
  analysisScope: z.enum(['full', 'profiles', 'chats']).optional(),
  includeConversations: z.boolean().optional(),
  analyzeIntelligence: z.boolean().optional(),
  messageGoal: z.string().optional(),
  tone: z.string().optional(),
  attachmentPath: z.string().optional(),
  emailSubject: z.string().optional(),
  emailCc: z.string().optional(),
  emailBcc: z.string().optional(),
  emailSignature: z.string().optional(),
  youtubeTitle: z.string().optional(),
  youtubeDescription: z.string().optional(),
  youtubeTags: z.string().optional(),
  youtubeVisibility: z.enum(['private', 'unlisted', 'public']).optional(),
  maxResults: z.number().int().positive().max(500).optional(),
  destination: z.enum(['sheet', 'artifact', 'inbox']).optional(),
  requireManualReview: z.boolean().optional(),
}).default({});

export const TaskRequestSchema = z.object({
  prompt: z.string().min(1),
  context: TaskContextSchema.optional().default({}),
  preferredBrowserMode: z.enum(['attached', 'managed', 'auto']).optional().default('auto'),
});

export const PairingCodeSchema = z.object({
  code: z.string(),
  expiresAt: z.string(),
});

export const AgentClaimSchema = z.object({
  code: z.string(),
  deviceName: z.string(),
  os: z.enum(['macos', 'windows', 'linux']),
  agentVersion: z.string(),
});

export const AgentTaskEventSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('task.created'), taskId: z.string(), prompt: z.string() }),
  z.object({
    type: z.literal('agent.status'),
    online: z.boolean(),
    browserAttached: z.boolean().optional(),
    connectionError: z.string().optional(),
    profileDirectory: z.string().optional(),
    tabs: z.number().int().nonnegative().optional(),
    mode: z.enum(['cdp', 'extension_bridge']).optional(),
    extensionLoaded: z.boolean().optional(),
    platform: z.string().optional(),
  }),
  z.object({ type: z.literal('plan.generated'), plan: ExecutionPlanSchema }),
  z.object({ type: z.literal('step.started'), stepId: z.string(), label: z.string() }),
  z.object({ type: z.literal('step.progress'), stepId: z.string(), message: z.string(), current: z.number().optional(), total: z.number().optional() }),
  z.object({ type: z.literal('step.failed'), stepId: z.string(), error: z.string(), retrying: z.boolean().optional() }),
  z.object({ type: z.literal('artifact.ready'), artifactId: z.string(), kind: z.enum(['csv', 'json', 'text', 'screenshot']), url: z.string().optional() }),
  z.object({ type: z.literal('task.completed'), summary: z.string() }),
  z.object({ type: z.literal('task.failed'), error: z.string() }),
  z.object({ type: z.literal('campaign.updated'), campaignId: z.string(), status: z.string() }),
]);

export function createId(prefix = 'id') {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}

export function safeParse(schema, payload) {
  const parsed = schema.safeParse(payload);
  if (!parsed.success) {
    const message = parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ');
    throw new Error(message || 'Invalid payload');
  }
  return parsed.data;
}
